### ISSUE TITLE
GitHub shortcode not honouring line breaks

### ISSUE THREAD

**Issue by stephlocke** [SufferMyJoy/dobsondev-shortcodes#1]
Am trialling you plugin for github file embeds but the rendered output isn't obviously different from the rest of the post body, but most importantly isn't respecting line breaks in the code itself. 

Wordpress 4.2.2, dobsondev 1.1.4
[Desired github file](https://github.com/stephlocke/tfsR/blob/master/.push_gh_pages.sh)
Shortcode: [embedGitHubContent owner="stephlocke" repo="tfsR" path=".push_gh_pages.sh"]
![Result](http://i.imgur.com/mQ5tb0l.png)

Am I doing something daft?

**Comment by stephlocke** [comment]
Wrapping the shortcode call in backticks seems to have done the trick but it might be worth documenting or adding these in by default

**Comment by dobsondev** [comment]
Hey @stephlocke, 

Sorry it took me a while to get this. I found a fix and I will be pushing it up later today both to GitHub and the WordPress plugin repository so you should see an available update soon. It was a really dumb case of forgetting to use the nl2br() function... 

Thank you so much for letting me know though - might not have caught it without you!
