### ISSUE TITLE
One possible bug and a feature request

### ISSUE THREAD

**Issue by igorpecovnik** [SufferMyJoy/dobsondev-shortcodes#3]
Everything is updated, Wordpress and all plugins.

Source:
https://github.com/igorpecovnik/lib/blob/master/documentation/logbook.md
Target:
http://www.armbian.com/logbook/
Command:
[embedGitHubContent owner="igorpecovnik" repo="lib" path="documentation/logbook.md" markdown="Yes"]

On the top of the file there is: **string(21) "DID NOT get Transient"**  on this file and here: http://www.armbian.com/documentation/ , other are o.k.

And a feature:

Is it possible to translate links, as on option?
https://github.com/igorpecovnik/lib/blob/master/documentation/user-faq.md#what-to-download
-> #what-to-download

**Comment by igorpecovnik** [comment]
Quick note - bug is not here anymore so it was a false alarm I guess, perhaps unrelated to plugin. Feature request stands - it would help me, perhaps generally.

Thanks for nice plugin.

**Comment by dobsondev** [comment]
I'll check about the translate link option, not sure the GitHub API has anything for that but I'll check it out.

**Comment by dobsondev** [comment]
Hey Igor,

So the only way I see being able to add your requested featured wouldn't be the most ideal way. What I could probably do is retrieve the entire `.md` file and then explode each section by a certain HTML tag, in this case it would be a `<h1>` tag. 

Once I do that you could select which section you wanted to display, something like an array. So in the end it would be something like this:

```
[embedGitHubMarkdownSection owner="igorpecovnik" repo="lib" path="documentation/user-faq.md" delimiter="<h1>" section="0"]
```

And then this shortcode would hopefully display just the **What to Download** section. You could also then use `section="1"` to display the **Legacy or Vanilla** section, `section="2"` to display the **How to check download authenticity?** section, etc...

If that's something you would want me to pursue let me know and I can give it a try. I think it might be a pretty unique use case for you but I don't mind including it if I can get it working.

**Comment by igorpecovnik** [comment]
Alex, what about if you add (generic) link to text inside `<h1>` in this exploded section and merge it back together to one document?

**Comment by dobsondev** [comment]
I can try to see if I can get that working.

**Comment by dobsondev** [comment]
Needless to say I couldn't get this working...
