### ISSUE TITLE
unable to use absolute image links in github markdown - oudated parsedown version?

### ISSUE THREAD

**Issue by mluerig** [SufferMyJoy/dobsondev-shortcodes#5]
After I got the shortcode to parse the github readme on my wordpress-homepage, I ran into an issue with links to images I am hosting in that github repo.
Somehow the absolute links to images I am providing in my Readme.md are converted to relative links that work from github/gh-pages, but of course not from my homepage. At first I thought this was an issue with markdown/parsedown, but one of the contributors of parsedown told me it was working fine for him. 
He suggested that the error could be due to additional parsing by the plugin or the use of an outdated parsedown version - see: https://github.com/erusev/parsedown/issues/577 

Would you mind having a look at that? Thanks!

**Comment by dobsondev** [comment]
I've updated the plugin to include the newest version of Parsedown. I've also taken a look and there is no additional parsing done by the plugin, I just retrieve the README file and then run it through Parsedown after it's been run through `base64_decode()`.

Hopefully that will solve the problem. Let me know!

**Comment by dobsondev** [comment]
I am going to mark this as closed for now. If you are still having issues after doing the update for the plugin just let me know and we can try figure out what's still going wrong.

Thanks!
